x-infisical-env: &infisical-env
  INFISICAL_TOKEN: ${INFISICAL_TOKEN}
  INFISICAL_PROJECT_ID: ${INFISICAL_PROJECT_ID}
  INFISICAL_API_URL: http://host.docker.internal:80

x-infisical-hosts: &infisical-hosts
  - "host.docker.internal:host-gateway"

services:
  api:
    image: api_image

    container_name: api_prod

    build:
      context: .
      target: prod

    environment:
      <<: *infisical-env
      INFISICAL_ENV: prod

    extra_hosts: *infisical-hosts

    ports:
      - "${API_EXTERNAL_PORT}:${API_INTERNAL_PORT}"

    depends_on:
      db:
        condition: service_healthy
    secrets:
      - db_password
  db:
    image: postgres:17
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_ADMIN}
      POSTGRES_PASSWORD: ${POSTGRES_ADMIN_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_APP_USER: ${POSTGRES_USER}
      POSTGRES_APP_PASSWORD: ${POSTGRES_USER_PASSWORD}
    secrets:
      - db_password
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d ${POSTGRES_DB} --quiet" ]
      interval: 1s
      timeout: 5s
      retries: 10
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/db/init.sh:/docker-entrypoint-initdb.d/init.sh
#      - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql

secrets:
  db_password:
    file: ./secrets/db_password

volumes:
  postgres_data: