x-infisical-env: &infisical-env
  INFISICAL_TOKEN: ${INFISICAL_TOKEN}
  INFISICAL_PROJECT_ID: ${INFISICAL_PROJECT_ID}
  INFISICAL_API_URL: http://host.docker.internal:80

x-infisical-hosts: &infisical-hosts
  - "host.docker.internal:host-gateway"

services:
  api:
    container_name: api_dev
    build:
      context: .
      target: dev
    image: api_dev
    environment:
      INFISICAL_ENV: dev

    develop:
      watch:
        - action: sync+restart
          path: ./src
          target: /app/src
        - action: rebuild
          path: package.json
        - action: sync+restart
          path: tsconfig.json
          target: /app/tsconfig.json
    ports: !override
      - "${API_INTERNAL_PORT}:${API_INTERNAL_PORT}"
  db_seed:
    image: api_dev
    depends_on:
      db:
        condition: service_healthy
    command: ["infisical", "run", "--projectId=${INFISICAL_PROJECT_ID}", "--env=dev", "--", "pnpm", "exec", "tsx", "db/seed.ts"]
    extra_hosts: *infisical-hosts
    environment:
      <<: *infisical-env
      INFISICAL_ENV: dev

