services:
  api:
    build:
      context: .
      target: dev
    container_name: core_api_dev
    develop:
      watch:
        - action: sync+restart
          path: ./src
          target: /app/src
        - action: rebuild
          path: package.json
        - action: sync+restart
          path: tsconfig.json
          target: /app/tsconfig.json
    ports: !override
      - "${API_INTERNAL_PORT}:${API_INTERNAL_PORT}"
