#!/bin/sh
set -eu

psql \
  -v ON_ERROR_STOP=1 \
  -v app_user="$POSTGRES_APP_USER" \
  -v app_password="$POSTGRES_APP_PASSWORD" \
  --username "$POSTGRES_USER" \
  --dbname "$POSTGRES_DB" <<'EOSQL'

CREATE ROLE :"app_user"
WITH LOGIN PASSWORD :'app_password';

GRANT CONNECT ON DATABASE :"DBNAME" TO :"app_user";

GRANT USAGE ON SCHEMA public TO :"app_user";

GRANT SELECT, INSERT, UPDATE, DELETE
ON ALL TABLES IN SCHEMA public
TO :"app_user";

GRANT USAGE, SELECT
ON ALL SEQUENCES IN SCHEMA public
TO :"app_user";

ALTER DEFAULT PRIVILEGES
IN SCHEMA public
GRANT SELECT, INSERT, UPDATE, DELETE
ON TABLES TO :"app_user";

ALTER DEFAULT PRIVILEGES
IN SCHEMA public
GRANT USAGE, SELECT
ON SEQUENCES TO :"app_user";

EOSQL